spring:
  profiles:
    active: dev
server:
  servlet:
    context-path: /Microsoft-User
mybatis:
  mapper-locations: classpath:config/mybatis/mapper/mapper_*.xml
  type-aliases-package: cloud.entity
logging:
  config: classpath:config/log/log.xml
fileupload:
  bufferSize: 4800
  fileDir:  E:\\file\\test
  bufferDir:  E:\\file\\buffer

